/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import BUS.NhaCungCapBUS;
import DTO.NhaCungCapDTO;
import java.util.ArrayList;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author dhuynh
 */
public class DlgChonNhaCungCap extends javax.swing.JDialog {
    DefaultTableModel modelDlgNhaCungCap;
    private NhaCungCapDTO nhaCungCapChon = null;
    public static String maNCC = null;
    /**
     * Creates new form DlgChonNhaCungCap
     */
    public DlgChonNhaCungCap() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setModal(true);
        this.setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txTimNhaCC = new javax.swing.JTextField();
        cbbTimNhaCC = new javax.swing.JComboBox<>();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblKQTKNhaCC = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        btnDlgChonNhaCC = new javax.swing.JButton();
        btnDlgThemNhaCC = new javax.swing.JButton();
        btnSuaDlgNhaCC = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Tìm kiếm", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 1, 20))); // NOI18N

        txTimNhaCC.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N

        cbbTimNhaCC.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        cbbTimNhaCC.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tất cả", "Mã nhà cung cấp", "Tên nhà cung cấp" }));
        cbbTimNhaCC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbbTimNhaCCActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(cbbTimNhaCC, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txTimNhaCC, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(53, 53, 53))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbbTimNhaCC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txTimNhaCC))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        tblKQTKNhaCC.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        tblKQTKNhaCC.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Mã nhà cung cấp", "Tên nhà cung cấp", "Địa chỉ", "Số điện thoại"
            }
        ));
        tblKQTKNhaCC.setRowHeight(25);
        jScrollPane1.setViewportView(tblKQTKNhaCC);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 499, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 293, Short.MAX_VALUE)
        );

        btnDlgChonNhaCC.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        btnDlgChonNhaCC.setText("Chọn");
        btnDlgChonNhaCC.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        btnDlgChonNhaCC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDlgChonNhaCCActionPerformed(evt);
            }
        });

        btnDlgThemNhaCC.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        btnDlgThemNhaCC.setText("Thêm");
        btnDlgThemNhaCC.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));

        btnSuaDlgNhaCC.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        btnSuaDlgNhaCC.setText("Sửa");
        btnSuaDlgNhaCC.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(btnDlgChonNhaCC, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnDlgThemNhaCC, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(76, 76, 76)
                .addComponent(btnSuaDlgNhaCC, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnDlgChonNhaCC, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE)
                    .addComponent(btnDlgThemNhaCC, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnSuaDlgNhaCC, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnDlgChonNhaCCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDlgChonNhaCCActionPerformed
        // TODO add your handling code here:
        int row = tblKQTKNhaCC.getSelectedRow();
        if (row < 0) {
            JOptionPane.showMessageDialog(null,"Bạn chưa chọn dòng cần chọn");
            return;
        }
        maNCC = tblKQTKNhaCC.getValueAt(row, 0) + "";
        //tblKQTKNhaCC.getValueAt(row, 1) + "";
        
        //loaiSPChon = new LoaiSPDTO(maLoai, tenLoai);
        
        this.dispose();
    }//GEN-LAST:event_btnDlgChonNhaCCActionPerformed

    private void cbbTimNhaCCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbbTimNhaCCActionPerformed
        // TODO add your handling code here:
        NhaCungCapBUS bus = new NhaCungCapBUS();
        ArrayList<NhaCungCapDTO> kq = new ArrayList<>();
        if(cbbTimNhaCC.getSelectedItem().equals("Mã nhà cung cấp")){
            NhaCungCapDTO ncc = bus.timkiemMaNCC(txTimNhaCC.getText());
            if(ncc != null){
                kq.add(ncc);
            }
        }
        else if(cbbTimNhaCC.getSelectedItem().equals("Tên nhà cung cấp")){
            kq = bus.timkiemTenNCC(txTimNhaCC.getText());
        }
        if(cbbTimNhaCC.getSelectedItem().equals("Tất cả")){
            showKQTKNhaCC(NhaCungCapBUS.listNCC);
            JOptionPane.showMessageDialog(null, "Kết quả tìm được: " + NhaCungCapBUS.listNCC.size());
        }
        else{
            showKQTKNhaCC(kq);
            JOptionPane.showMessageDialog(null, "Kết quả tìm được: " + kq.size());
        }
    }//GEN-LAST:event_cbbTimNhaCCActionPerformed

    public void showKQTKNhaCC(ArrayList<NhaCungCapDTO> ds){
        Vector header = new Vector();
        header.add("Mã nhà cung cấp");
        header.add("Tên nhà cung cấp");
        header.add("Địa chỉ");
        header.add("Số điện thoại");
                
        modelDlgNhaCungCap = new DefaultTableModel(header,0);
        
        for(NhaCungCapDTO nv : ds){
            Vector row = new Vector();
            row.add(nv.getIdNCC());
            row.add(nv.getTenNCC());
            row.add(nv.getDiachiNCC());
            row.add(nv.getSdtNCC());
            modelDlgNhaCungCap.addRow(row);
        }
        tblKQTKNhaCC.setModel(modelDlgNhaCungCap);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DlgChonNhaCungCap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DlgChonNhaCungCap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DlgChonNhaCungCap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DlgChonNhaCungCap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                DlgChonNhaCungCap dialog = new DlgChonNhaCungCap();
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDlgChonNhaCC;
    private javax.swing.JButton btnDlgThemNhaCC;
    private javax.swing.JButton btnSuaDlgNhaCC;
    private javax.swing.JComboBox<String> cbbTimNhaCC;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblKQTKNhaCC;
    private javax.swing.JTextField txTimNhaCC;
    // End of variables declaration//GEN-END:variables
}
