/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import BUS.ChiTietKhuyenMaiBUS;
import BUS.KhuyenMaiBUS;
import DTO.ChiTietKhuyenMaiDTO;
import DTO.KhuyenMaiDTO;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author 
 */
public class DlgChonKhuyenMai extends javax.swing.JDialog {

    public static String maKM = null;
   // public static int phantramKM = 0;
    DefaultTableModel modelDlgKM;
    /**
     * Creates new form DlgChonKhuyenMai
     */
    public DlgChonKhuyenMai() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setModal(true);
        this.setResizable(false);
        
        ArrayList<KhuyenMaiDTO> dskm = new ArrayList<>();
        for(KhuyenMaiDTO km : KhuyenMaiBUS.listKM){
            if(km.getMaKM().equals(MainFrameGUI.maKM)){
                dskm.add(km);
                showKQTKKhuyenMai(dskm); //show km thỏa
            }
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        cbbTimKM = new javax.swing.JComboBox<>();
        txTimKM = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblKQTKKhuyenMai = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Tìm kiếm", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 1, 20))); // NOI18N

        cbbTimKM.setEditable(true);
        cbbTimKM.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        cbbTimKM.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tất cả", "Mã khuyến mãi", "Tên khuyến mãi", "Điều kiện" }));
        cbbTimKM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbbTimKMActionPerformed(evt);
            }
        });

        txTimKM.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(cbbTimKM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(txTimKM, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbbTimKM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txTimKM))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tblKQTKKhuyenMai.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        tblKQTKKhuyenMai.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Mã khuyến mãi", "Tên khuyến mãi", "Ngày bắt đầu", "Ngày kết thúc", "Điều kiện"
            }
        ));
        tblKQTKKhuyenMai.setRowHeight(25);
        tblKQTKKhuyenMai.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblKQTKKhuyenMaiMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblKQTKKhuyenMai);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 355, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbbTimKMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbbTimKMActionPerformed
        // TODO add your handling code here:
        KhuyenMaiBUS bus=new KhuyenMaiBUS();
        ArrayList<KhuyenMaiDTO> kq=new ArrayList<>();
        
        if(cbbTimKM.getSelectedItem().equals("Mã khuyến mãi")){
            KhuyenMaiDTO km=bus.timkiemMaKM(txTimKM.getText());
            if(km!=null){
                kq.add(km);
            }
        }
        else if(cbbTimKM.getSelectedItem().equals("Tên khuyến mãi")){
            kq=bus.timkiemTenKM(txTimKM.getText());
        }
        else if(cbbTimKM.getSelectedItem().equals("Điều kiện")){
            kq=bus.timkiemDieuKienKM(Integer.parseInt(txTimKM.getText()));
        }
        if(cbbTimKM.getSelectedItem().equals("Tất cả")){
            showKQTKKhuyenMai(KhuyenMaiBUS.listKM);
            JOptionPane.showMessageDialog(null, "Kết quả tìm được: " + KhuyenMaiBUS.listKM.size());
        }
        else if(kq.size()==0){
            showKQTKKhuyenMai(kq);
            JOptionPane.showMessageDialog(null, "Không có khuyến mãi mà bạn cần tìm");
        }
        else{
            showKQTKKhuyenMai(kq);
            JOptionPane.showMessageDialog(null, "Kết quả tìm được: " + kq.size());
        }
    }//GEN-LAST:event_cbbTimKMActionPerformed

    private void tblKQTKKhuyenMaiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblKQTKKhuyenMaiMouseClicked
        // TODO add your handling code here:
        maKM=null;
        int row = tblKQTKKhuyenMai.getSelectedRow();
        if (row < 0) {
            JOptionPane.showMessageDialog(null,"Bạn chưa chọn dòng cần chọn");
            return;
        }
        maKM = tblKQTKKhuyenMai.getValueAt(row, 0) + "";
//        for(ChiTietKhuyenMaiDTO ctkm : ChiTietKhuyenMaiBUS.listCTKM){
//            if(ctkm.getMaKM().equals(maKM)){
//                phantramKM = ctkm.getPhantramKM();
//            }
//        }
        
        this.dispose();
    }//GEN-LAST:event_tblKQTKKhuyenMaiMouseClicked

    public void showKQTKKhuyenMai(ArrayList<KhuyenMaiDTO> ds){
        Vector header = new Vector();
        header.add("Mã khuyến mãi");
        header.add("Tên khuyến mãi");
        header.add("Ngày bắt đầu");
        header.add("Ngày kết thúc");
        header.add("Điều kiện");
        
        modelDlgKM = new DefaultTableModel(header,0);
        SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
        for(KhuyenMaiDTO km : ds){
            Vector row = new Vector();
            row.add(km.getMaKM());
            row.add(km.getTenKM());
            row.add(sdf.format(km.getNgaybdKM()));
            row.add(sdf.format(km.getNgayktKM()));
            row.add(km.getDieukienKM());
            
            modelDlgKM.addRow(row);
        }
        tblKQTKKhuyenMai.setModel(modelDlgKM);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DlgChonKhuyenMai.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DlgChonKhuyenMai.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DlgChonKhuyenMai.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DlgChonKhuyenMai.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                DlgChonKhuyenMai dialog = new DlgChonKhuyenMai();
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cbbTimKM;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblKQTKKhuyenMai;
    private javax.swing.JTextField txTimKM;
    // End of variables declaration//GEN-END:variables
}
