/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import BUS.KhachHangBUS;
import DTO.KhachHangDTO;
import java.util.ArrayList;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author 
 */
public class DlgChonKhachHang extends javax.swing.JDialog {
    public static String maKH = null;    
    DefaultTableModel modelDlgKH;
    /**
     * Creates new form DlgChonKhachHang
     */
    public DlgChonKhachHang() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setModal(true);
        this.setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        cbbTimKH = new javax.swing.JComboBox<>();
        txTimKH = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblKQTKKhachHang = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        btnDlgChonKH = new javax.swing.JButton();
        btnDlgThemKH = new javax.swing.JButton();
        btnDlgSuaKH = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Tìm kiếm", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 1, 20))); // NOI18N

        cbbTimKH.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        cbbTimKH.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tất cả", "Mã khách hàng", "Họ khách hàng", "Tên khách hàng", "Giới tính" }));
        cbbTimKH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbbTimKHActionPerformed(evt);
            }
        });

        txTimKH.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(94, Short.MAX_VALUE)
                .addComponent(cbbTimKH, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(txTimKH, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(63, 63, 63))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cbbTimKH, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
                    .addComponent(txTimKH))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        tblKQTKKhachHang.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        tblKQTKKhachHang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Mã khách hàng", "Họ khách hàng", "Tên khách hàng", "Giới tính", "Địa chỉ", "SDT"
            }
        ));
        tblKQTKKhachHang.setRowHeight(25);
        jScrollPane1.setViewportView(tblKQTKKhachHang);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 346, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );

        btnDlgChonKH.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        btnDlgChonKH.setText("Chọn");
        btnDlgChonKH.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        btnDlgChonKH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDlgChonKHActionPerformed(evt);
            }
        });

        btnDlgThemKH.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        btnDlgThemKH.setText("Thêm");
        btnDlgThemKH.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        btnDlgSuaKH.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        btnDlgSuaKH.setText("Sửa");
        btnDlgSuaKH.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(btnDlgChonKH, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnDlgThemKH, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(100, 100, 100)
                .addComponent(btnDlgSuaKH, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDlgChonKH, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDlgThemKH, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDlgSuaKH, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnDlgChonKHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDlgChonKHActionPerformed
        // TODO add your handling code here:
        int row = tblKQTKKhachHang.getSelectedRow();
        if (row < 0) {
            JOptionPane.showMessageDialog(null,"Bạn chưa chọn dòng cần chọn");
            return;
        }
        maKH = tblKQTKKhachHang.getValueAt(row, 0) + "";
        
        this.dispose();
    }//GEN-LAST:event_btnDlgChonKHActionPerformed

    private void cbbTimKHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbbTimKHActionPerformed
        // TODO add your handling code here:
        KhachHangBUS bus=new KhachHangBUS();
        ArrayList<KhachHangDTO> kq=new ArrayList<>();
        
        if(cbbTimKH.getSelectedItem().equals("Mã khách hàng")){
            KhachHangDTO kh=bus.timKiemMaKH(txTimKH.getText());
            if(kh!=null){
                kq.add(kh);
            }
        }
        else if(cbbTimKH.getSelectedItem().equals("Họ khách hàng")){
            kq=bus.timKiemHoKH(txTimKH.getText());
        }
        else if(cbbTimKH.getSelectedItem().equals("Tên khách hàng")){
            kq=bus.timKiemTenKH(txTimKH.getText());
        }
        else if(cbbTimKH.getSelectedItem().equals("Giới tính")){
            kq=bus.timKiemGioiTinh(txTimKH.getText());
        }
        if(cbbTimKH.getSelectedItem().equals("Tất cả")){
            showKQTKKhachHang(KhachHangBUS.dskh);
            JOptionPane.showMessageDialog(null, "Kết quả tìm được: " + KhachHangBUS.dskh.size());
        }
        else if(kq.size()==0){
            JOptionPane.showMessageDialog(null, "Không có khách hàng mà bạn cần tìm");
        }
        else{
            showKQTKKhachHang(kq);
            JOptionPane.showMessageDialog(null, "Kết quả tìm được: " + kq.size());
        }
    }//GEN-LAST:event_cbbTimKHActionPerformed

    public void showKQTKKhachHang(ArrayList<KhachHangDTO> ds){
        Vector header = new Vector();
        header.add("Mã khách hàng");
        header.add("Họ khách hàng");
        header.add("Tên khách hàng");
        header.add("Giới tính");
        header.add("Địa chỉ");
        header.add("SDT");
        
        modelDlgKH = new DefaultTableModel(header,0);
        
        for(KhachHangDTO kh : ds){
            Vector row = new Vector();
            row.add(kh.getMaKH());
            row.add(kh.getHoKH());
            row.add(kh.getTenKH());
            row.add(kh.getGioitinh());
            row.add(kh.getDiachi());
            row.add(kh.getSdt());
            
            modelDlgKH.addRow(row);
        }
        tblKQTKKhachHang.setModel(modelDlgKH);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DlgChonKhachHang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DlgChonKhachHang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DlgChonKhachHang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DlgChonKhachHang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                DlgChonKhachHang dialog = new DlgChonKhachHang();
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDlgChonKH;
    private javax.swing.JButton btnDlgSuaKH;
    private javax.swing.JButton btnDlgThemKH;
    private javax.swing.JComboBox<String> cbbTimKH;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblKQTKKhachHang;
    private javax.swing.JTextField txTimKH;
    // End of variables declaration//GEN-END:variables
}
