/*
 * To change this license header, choose License Headers sin Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import BUS.KhachHangBUS;
import DTO.KhachHangDTO;
import Tool.ID;
import java.awt.HeadlessException;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.util.ArrayList;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ASUS
 */
public class KhachHangGUI extends javax.swing.JFrame {
    DefaultTableModel model;

    /**
     * Creates new form Customer
     */
    public KhachHangGUI(){
        initComponents();
        docDSKH();
        txMakh.setText(ID.createNewKH());
        
        txHokh.addKeyListener(new KeyAdapter() {
            @Override
            public void keyPressed(KeyEvent e){
                if(e.getKeyCode()==KeyEvent.VK_ENTER)
                    txTenkh.requestFocus();
            }
        });
        txTenkh.addKeyListener(new KeyAdapter() {
            @Override
            public void keyPressed(KeyEvent e){
                if(e.getKeyCode()==KeyEvent.VK_ENTER)
                    txDC.requestFocus();
            }
        });
        txDC.addKeyListener(new KeyAdapter() {
            @Override
            public void keyPressed(KeyEvent e){
                if(e.getKeyCode()==KeyEvent.VK_ENTER)
                    txSDT.requestFocus();
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        p1 = new javax.swing.JPanel();
        lbTTkhachhang = new javax.swing.JLabel();
        p2 = new javax.swing.JPanel();
        lbMakh = new javax.swing.JLabel();
        lbHokh = new javax.swing.JLabel();
        lbTenkh = new javax.swing.JLabel();
        txMakh = new javax.swing.JTextField();
        txHokh = new javax.swing.JTextField();
        txTenkh = new javax.swing.JTextField();
        lbGT = new javax.swing.JLabel();
        cbGTNam = new javax.swing.JCheckBox();
        cbGTNu = new javax.swing.JCheckBox();
        lbDC = new javax.swing.JLabel();
        lbSDT = new javax.swing.JLabel();
        txDC = new javax.swing.JTextField();
        txSDT = new javax.swing.JTextField();
        btThem = new javax.swing.JButton();
        btSua = new javax.swing.JButton();
        btLammoi = new javax.swing.JButton();
        btXoa = new javax.swing.JButton();
        txTimKiem = new javax.swing.JTextField();
        btTimKiem = new javax.swing.JButton();
        cbbTimKiem = new javax.swing.JComboBox<>();
        p3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbKhachhang = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        lbTong = new javax.swing.JLabel();
        txTong = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 102));

        p1.setBackground(new java.awt.Color(204, 204, 255));
        p1.setForeground(new java.awt.Color(0, 0, 204));

        lbTTkhachhang.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        lbTTkhachhang.setForeground(new java.awt.Color(0, 0, 102));
        lbTTkhachhang.setText("Thông tin khách hàng");

        javax.swing.GroupLayout p1Layout = new javax.swing.GroupLayout(p1);
        p1.setLayout(p1Layout);
        p1Layout.setHorizontalGroup(
            p1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p1Layout.createSequentialGroup()
                .addGap(127, 127, 127)
                .addComponent(lbTTkhachhang)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        p1Layout.setVerticalGroup(
            p1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, p1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbTTkhachhang, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        p2.setBackground(new java.awt.Color(204, 204, 255));

        lbMakh.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        lbMakh.setText("Mã khách hàng");

        lbHokh.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        lbHokh.setText("Họ khách hàng");

        lbTenkh.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        lbTenkh.setText("Tên khách hàng");

        txMakh.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        txMakh.setEnabled(false);

        txHokh.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N

        txTenkh.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N

        lbGT.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        lbGT.setText("Giới tính");

        cbGTNam.setBackground(new java.awt.Color(204, 204, 255));
        buttonGroup1.add(cbGTNam);
        cbGTNam.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        cbGTNam.setText("Nam");
        cbGTNam.setPreferredSize(new java.awt.Dimension(73, 40));

        cbGTNu.setBackground(new java.awt.Color(204, 204, 255));
        buttonGroup1.add(cbGTNu);
        cbGTNu.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        cbGTNu.setText("Nữ");

        lbDC.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        lbDC.setText("Địa chỉ ");

        lbSDT.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        lbSDT.setText("SĐT");

        txDC.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        txDC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txDCActionPerformed(evt);
            }
        });

        txSDT.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N

        btThem.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        btThem.setText("Thêm");
        btThem.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        btThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btThemActionPerformed(evt);
            }
        });

        btSua.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        btSua.setText("Sửa");
        btSua.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        btSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSuaActionPerformed(evt);
            }
        });

        btLammoi.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        btLammoi.setText("Làm mới");
        btLammoi.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        btLammoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLammoiActionPerformed(evt);
            }
        });

        btXoa.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        btXoa.setText("Xóa");
        btXoa.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        btXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btXoaActionPerformed(evt);
            }
        });

        txTimKiem.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N

        btTimKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btTimKiemActionPerformed(evt);
            }
        });

        cbbTimKiem.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Mã KH", "Họ KH", "Tên KH", "Giới tính" }));

        javax.swing.GroupLayout p2Layout = new javax.swing.GroupLayout(p2);
        p2.setLayout(p2Layout);
        p2Layout.setHorizontalGroup(
            p2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(p2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbTenkh)
                    .addComponent(btThem, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(p2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(lbHokh)
                        .addComponent(lbMakh)))
                .addGroup(p2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, p2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btSua, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(94, 94, 94))
                    .addGroup(p2Layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addGroup(p2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txHokh, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txMakh, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txTenkh, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(57, 57, 57)))
                .addGroup(p2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(p2Layout.createSequentialGroup()
                        .addGroup(p2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(p2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lbSDT)
                                .addComponent(lbDC, javax.swing.GroupLayout.Alignment.TRAILING))
                            .addComponent(lbGT, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(57, 57, 57)
                        .addGroup(p2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, p2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(cbGTNam, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txDC, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txSDT, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(cbGTNu, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(p2Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(p2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(p2Layout.createSequentialGroup()
                                .addComponent(btXoa, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 110, Short.MAX_VALUE)
                                .addComponent(btLammoi, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(p2Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(txTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cbbTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        p2Layout.setVerticalGroup(
            p2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, p2Layout.createSequentialGroup()
                .addGroup(p2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(p2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(p2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(p2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(cbGTNam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lbGT))
                            .addComponent(cbGTNu))
                        .addGap(18, 18, 18)
                        .addGroup(p2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbDC)
                            .addComponent(txDC, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(p2Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(p2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbMakh)
                            .addComponent(txMakh, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(p2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txHokh, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbHokh))))
                .addGap(21, 21, 21)
                .addGroup(p2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbTenkh)
                    .addComponent(lbSDT)
                    .addComponent(txSDT, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txTenkh, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45)
                .addGroup(p2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btThem, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btSua, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btXoa, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btLammoi, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addGroup(p2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btTimKiem, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txTimKiem, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbbTimKiem, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        p3.setBackground(new java.awt.Color(204, 204, 255));

        tbKhachhang.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        tbKhachhang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Mã khách hàng", "Họ khách hàng", "Tên khách hàng", "Giới tính", "Địa chỉ", "SDT"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tbKhachhang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbKhachhangMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tbKhachhang);

        jScrollPane1.setViewportView(jScrollPane2);

        javax.swing.GroupLayout p3Layout = new javax.swing.GroupLayout(p3);
        p3.setLayout(p3Layout);
        p3Layout.setHorizontalGroup(
            p3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1042, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        p3Layout.setVerticalGroup(
            p3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p3Layout.createSequentialGroup()
                .addContainerGap(31, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));

        lbTong.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        lbTong.setText("Tổng");

        txTong.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txTong, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lbTong, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(105, 105, 105))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbTong, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txTong, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(53, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(p1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(p2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(p3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 3, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(p1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(p2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(p3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btThemActionPerformed
        // TODO add your handling code here:
        
        try {
            KhachHangDTO kh = new KhachHangDTO();
            kh.setMaKH(ID.createNewKH());
         
            if(cbGTNam.isSelected()){
                kh.setGioitinh("Nam");
            }
            else if(cbGTNu.isSelected()){
                kh.setGioitinh("Nữ");
            }
            if(!cbGTNam.isSelected() && !cbGTNu.isSelected()){
                JOptionPane.showMessageDialog(null, "Hãy chọn giới tính");
            }
            else if(txHokh.getText().equals("")){
                JOptionPane.showMessageDialog(null, "Họ không được để trống");
            }
            else if(txTenkh.getText().equals("")){
                JOptionPane.showMessageDialog(null, "Tên không được để trống");
            }
            else if(!checkPhone(txSDT.getText())){
                JOptionPane.showMessageDialog(null, "Số điện thoại phải đủ 10 số");
            }
            else{
                kh.setHoKH(txHokh.getText());
                kh.setTenKH(txTenkh.getText());
                kh.setDiachi(txDC.getText());
                kh.setSdt(txSDT.getText()); 

                KhachHangBUS bus = new KhachHangBUS();
                bus.themKH(kh);

                JOptionPane.showMessageDialog(null, "Thêm nhân viên thành công");

                txMakh.setText(ID.createNewKH());
            }
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Thêm nhân viên không thành công");
        }
        showDSKH(KhachHangBUS.dskh);  //để đây thì jtable tự sắp xếp lại
    }//GEN-LAST:event_btThemActionPerformed

    private void txDCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txDCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txDCActionPerformed

    private void btLammoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLammoiActionPerformed
        // TODO add your handling code here:
        txMakh.setText(ID.createNewKH());
        txHokh.setText("");
        txTenkh.setText("");
        txDC.setText("");
        txSDT.setText("");
        cbGTNam.setSelected(false);
        cbGTNu.setSelected(false);
    }//GEN-LAST:event_btLammoiActionPerformed

    private void btSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSuaActionPerformed
        // TODO add your handling code here:
        int i= tbKhachhang.getSelectedRow();
                if(i>=0){
                    try {
                        KhachHangDTO kh = new KhachHangDTO();
                        kh.setMaKH(txMakh.getText());
                        kh.setHoKH(txHokh.getText());
                        kh.setTenKH(txTenkh.getText());

                        if(cbGTNam.isSelected()){
                            kh.setGioitinh("Nam");
                        }
                        else if(cbGTNu.isSelected()){
                            kh.setGioitinh("Nữ");
                        }
                        kh.setSdt(txSDT.getText());
                        kh.setDiachi(txDC.getText());
                        KhachHangBUS bus = new KhachHangBUS();
                        bus.suaKH(kh);
                        bus.docDSKH();
                        showDSKH(KhachHangBUS.dskh);
                    } catch (Exception ex) {
                        JOptionPane.showMessageDialog(null, "Sửa khách hàng không thành công");
                    }
                }
                else{
                    JOptionPane.showMessageDialog(null, "Mời bạn chọn dòng cần sửa");
                }
    
    }//GEN-LAST:event_btSuaActionPerformed

    private void btXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btXoaActionPerformed
        // TODO add your handling code here:
        String ma = txMakh.getText();
        int i= tbKhachhang.getSelectedRow();
            try {
                if(i>=0){
                        KhachHangBUS bus = new KhachHangBUS();
                        bus.xoaKH(ma);
                        bus.docDSKH();
                        showDSKH(KhachHangBUS.dskh);
                }
            } catch (Exception ex) {
                Logger.getLogger(KhachHangGUI.class.getName()).log(Level.SEVERE, null, ex);
            }
    }//GEN-LAST:event_btXoaActionPerformed

    private void tbKhachhangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbKhachhangMouseClicked
        // TODO add your handling code here:
        
        int i = tbKhachhang.getSelectedRow();
                if(i>=0){
                    txMakh.setText(tbKhachhang.getValueAt(i, 0) + "");
                    txHokh.setText(tbKhachhang.getValueAt(i, 1) + "");
                    txTenkh.setText(tbKhachhang.getValueAt(i, 2) + "");
                    txDC.setText(tbKhachhang.getValueAt(i, 3) + "");
                    txSDT.setText(tbKhachhang.getValueAt(i, 4) + "");
        }
                    
    }//GEN-LAST:event_tbKhachhangMouseClicked

    private void btTimKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btTimKiemActionPerformed
         //TODO add your handling code here:
        KhachHangBUS bus=new KhachHangBUS();
            ArrayList<KhachHangDTO> kq=new ArrayList<>();
                if(cbbTimKiem.getSelectedItem().equals("Mã KH")){
                    KhachHangDTO kh=bus.timKiemMaKH(txTimKiem.getText());
                    if(kh!=null){
                        kq.add(kh);
                    }
                }
                else if(cbbTimKiem.getSelectedItem().equals("Họ KH")){
                    kq=bus.timKiemHoKH(txTimKiem.getText());
                }
                else if(cbbTimKiem.getSelectedItem().equals("Tên KH")){
                    kq=bus.timKiemTenKH(txTimKiem.getText());
                }
                else if(cbbTimKiem.getSelectedItem().equals("Giới tính")){
                    kq=bus.timKiemGioiTinh(txTimKiem.getText());
                }
                if(kq.size()==0){
                    JOptionPane.showMessageDialog(null, "không có khách hàng mà bạn cần tìm");
                }
                else{
                    showDSKH(kq);
                }
    }//GEN-LAST:event_btTimKiemActionPerformed
    
    public void docDSKH(){
    KhachHangBUS bus = new KhachHangBUS();
        if(KhachHangBUS.dskh == null){
            bus.docDSKH();
        }
        Vector header = new Vector();
        header.add("Mã khách hàng");
        header.add("Họ khách hàng");
        header.add("Tên khách hàng");
        header.add("Giới tính");
        header.add("Địa chỉ");
        header.add("SDT");
      
        model = new DefaultTableModel(header,0);
                        
        for(KhachHangDTO kh : KhachHangBUS.dskh){
            Vector row = new Vector();
            row.add(kh.getMaKH());
            row.add(kh.getHoKH());
            row.add(kh.getTenKH());
            row.add(kh.getGioitinh());
            row.add(kh.getDiachi());
            row.add(kh.getSdt());

            model.addRow(row);
        }
        tbKhachhang.setModel(model);
    }
    public void showDSKH(ArrayList<KhachHangDTO> ds){
        Vector header = new Vector();
        header.add("Mã khách hàng");
        header.add("Họ khách hàng");
        header.add("Tên khách hàng");
        header.add("Giới tính");
        header.add("Địa chỉ");
        header.add("SDT");
       
        model = new DefaultTableModel(header,0);
        
        for(KhachHangDTO kh : ds){
            Vector row = new Vector();
            row.add(kh.getMaKH());
            row.add(kh.getHoKH());
            row.add(kh.getTenKH());
            row.add(kh.getGioitinh());
            row.add(kh.getDiachi());
            row.add(kh.getSdt());
            
            model.addRow(row);
        }
        tbKhachhang.setModel(model);
        //tbKhachhang.getRowSorter().toggleSortOrder(0);//sắp xếp lại cho thứ tự trong jtable giống vs thứ tự trong arraylist
}
    public boolean checkPhone(String str){
        // Bieu thuc chinh quy mo ta dinh dang so dien thoai
        String reg = "^(0|\\+84)(\\s|\\.)?((3[2-9])|(5[689])|(7[06-9])|(8[1-689])|(9[0-46-9]))(\\d)(\\s|\\.)?(\\d{3})(\\s|\\.)?(\\d{3})$";

        // Kiem tra dinh dang
        boolean kt = str.matches(reg);

        if (kt == false) {
            return false;
        } else {
            //System.out.println("Số điện thoại hợp lệ");
            return true;
        }
    }
    
   
     /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(KhachHangGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(KhachHangGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(KhachHangGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(KhachHangGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                KhachHangGUI frame;
                try {
                    frame = new KhachHangGUI();
                    frame.setLocationRelativeTo(null);
                    frame.setVisible(true);
                } catch (Exception ex) {
                    Logger.getLogger(KhachHangGUI.class.getName()).log(Level.SEVERE, null, ex);
                }
                
//                new KhachHangDTO().setLocationRelativeTo(null);
//                new KhachHangDTO().setVisible(true);
               
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btLammoi;
    private javax.swing.JButton btSua;
    private javax.swing.JButton btThem;
    private javax.swing.JButton btTimKiem;
    private javax.swing.JButton btXoa;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JCheckBox cbGTNam;
    private javax.swing.JCheckBox cbGTNu;
    private javax.swing.JComboBox<String> cbbTimKiem;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lbDC;
    private javax.swing.JLabel lbGT;
    private javax.swing.JLabel lbHokh;
    private javax.swing.JLabel lbMakh;
    private javax.swing.JLabel lbSDT;
    private javax.swing.JLabel lbTTkhachhang;
    private javax.swing.JLabel lbTenkh;
    private javax.swing.JLabel lbTong;
    private javax.swing.JPanel p1;
    private javax.swing.JPanel p2;
    private javax.swing.JPanel p3;
    private javax.swing.JTable tbKhachhang;
    private javax.swing.JTextField txDC;
    private javax.swing.JTextField txHokh;
    private javax.swing.JTextField txMakh;
    private javax.swing.JTextField txSDT;
    private javax.swing.JTextField txTenkh;
    private javax.swing.JTextField txTimKiem;
    private javax.swing.JTextField txTong;
    // End of variables declaration//GEN-END:variables
}
