/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import BUS.LoaiSPBUS;
import DTO.LoaiSPDTO;
import Tool.ID;
import java.util.ArrayList;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ASUS
 */
public class LoaiSPGUI extends javax.swing.JFrame {
    DefaultTableModel model;
    /**
     * Creates new form ProductType
     */
    public LoaiSPGUI() {
        initComponents();
        docDSLoaiSP();
        txMaloai.setText(ID.createNewLoaiSP());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lbTTloaisp = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        lbMaloai = new javax.swing.JLabel();
        lbTenloai = new javax.swing.JLabel();
        txMaloai = new javax.swing.JTextField();
        txTenloai = new javax.swing.JTextField();
        btThem = new javax.swing.JButton();
        btSua = new javax.swing.JButton();
        btXoa = new javax.swing.JButton();
        btlammoi = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbloaisp = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));

        lbTTloaisp.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        lbTTloaisp.setForeground(new java.awt.Color(0, 0, 102));
        lbTTloaisp.setIcon(new javax.swing.ImageIcon("D:\\java\\MaketMini\\src\\icon\\icons8-ibeacon-48.png")); // NOI18N
        lbTTloaisp.setText("Thông tin loại sản phẩm");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(156, 156, 156)
                .addComponent(lbTTloaisp)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbTTloaisp)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(204, 204, 255));

        lbMaloai.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        lbMaloai.setText("Mã loại");

        lbTenloai.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        lbTenloai.setText("Tên loại");

        txMaloai.setEditable(false);
        txMaloai.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txMaloai.setEnabled(false);

        txTenloai.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        btThem.setBackground(new java.awt.Color(255, 255, 255));
        btThem.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        btThem.setIcon(new javax.swing.ImageIcon("D:\\java\\MaketMini\\src\\icon\\icons8-add-24.png")); // NOI18N
        btThem.setText("Thêm");
        btThem.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        btThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btThemActionPerformed(evt);
            }
        });

        btSua.setBackground(new java.awt.Color(255, 255, 255));
        btSua.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        btSua.setIcon(new javax.swing.ImageIcon("D:\\java\\MaketMini\\src\\icon\\icons8-edit-24.png")); // NOI18N
        btSua.setText("Sửa");
        btSua.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        btSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSuaActionPerformed(evt);
            }
        });

        btXoa.setBackground(new java.awt.Color(255, 255, 255));
        btXoa.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        btXoa.setIcon(new javax.swing.ImageIcon("D:\\java\\MaketMini\\src\\icon\\icons8-delete-24.png")); // NOI18N
        btXoa.setText("Xóa");
        btXoa.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        btXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btXoaActionPerformed(evt);
            }
        });

        btlammoi.setBackground(new java.awt.Color(255, 255, 255));
        btlammoi.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        btlammoi.setIcon(new javax.swing.ImageIcon("D:\\java\\MaketMini\\src\\icon\\icons8-refresh-24.png")); // NOI18N
        btlammoi.setText("Làm mới");
        btlammoi.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        btlammoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btlammoiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(126, 126, 126)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(lbMaloai)
                        .addGap(46, 46, 46)
                        .addComponent(txMaloai, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(btThem, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(71, 71, 71)
                        .addComponent(btSua, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(91, 91, 91)
                        .addComponent(lbTenloai)
                        .addGap(49, 49, 49)
                        .addComponent(txTenloai, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(81, 81, 81)
                        .addComponent(btXoa, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(75, 75, 75)
                        .addComponent(btlammoi, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(109, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txMaloai, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbTenloai)
                    .addComponent(txTenloai, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbMaloai))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 71, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btThem, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btSua, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btXoa, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btlammoi, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(61, 61, 61))
        );

        jPanel3.setBackground(new java.awt.Color(204, 204, 255));

        tbloaisp.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        tbloaisp.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Mã loại", "Tên loại"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tbloaisp.setRowHeight(20);
        tbloaisp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbloaispMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbloaisp);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 203, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btlammoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btlammoiActionPerformed
        // TODO add your handling code here:
        txMaloai.setText(ID.createNewLoaiSP());
        txTenloai.setText("");
        
    }//GEN-LAST:event_btlammoiActionPerformed

    private void btThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btThemActionPerformed
        // TODO add your handling code here:
        try {
            LoaiSPDTO loaisp = new LoaiSPDTO();
            loaisp.setMaloai(ID.createNewLoaiSP());
            loaisp.setTenloai(txTenloai.getText());

            LoaiSPBUS bus = new  LoaiSPBUS();
            bus.themLoaiSP(loaisp);

            JOptionPane.showMessageDialog(null, "Thêm loại sản phẩm thành công");

            txMaloai.setText(ID.createNewLoaiSP());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Thêm loại sản phẩm không thành công");
        }
        showDSLoaiSP(LoaiSPBUS.dsLoaiSP);  //để đây thì jtable tự sắp xếp lại
    }//GEN-LAST:event_btThemActionPerformed

    private void btSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSuaActionPerformed
        // TODO add your handling code here:
        int i= tbloaisp.getSelectedRow();
                if(i>=0){
                    try {
                        LoaiSPDTO loaisp = new LoaiSPDTO();
                        loaisp.setMaloai(txMaloai.getText());
                        loaisp.setTenloai(txTenloai.getText());
                        
                        LoaiSPBUS bus = new LoaiSPBUS();
                        bus.suaLoaiSP(loaisp);
                        bus.docDSLoaiSP();
                        showDSLoaiSP(LoaiSPBUS.dsLoaiSP);
                        
                    } catch (Exception ex) {
                        JOptionPane.showMessageDialog(null, "Sửa loại sản phẩm không thành công");
                    }
                }
                else{
                    JOptionPane.showMessageDialog(null, "Mời bạn chọn dòng cần sửa");
                }
    }//GEN-LAST:event_btSuaActionPerformed

    private void btXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btXoaActionPerformed
        // TODO add your handling code here:
        String ma = txMaloai.getText();
        int i= tbloaisp.getSelectedRow();
            try {
                if(i>=0){
                        LoaiSPBUS bus = new LoaiSPBUS();
                        bus.xoaLoaiSP(ma);
                        bus.docDSLoaiSP();
                        showDSLoaiSP(LoaiSPBUS.dsLoaiSP);
                }
            } catch (Exception ex) {
                Logger.getLogger(KhachHangGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btXoaActionPerformed

    private void tbloaispMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbloaispMouseClicked
        // TODO add your handling code here:
        int i = tbloaisp.getSelectedRow();
        if(i>=0){
            txMaloai.setText(tbloaisp.getValueAt(i, 0)+ "");
            txTenloai.setText(tbloaisp.getValueAt(i, 1) + "");
        }
    }//GEN-LAST:event_tbloaispMouseClicked

    public void docDSLoaiSP(){
    LoaiSPBUS bus = new LoaiSPBUS();
        if(LoaiSPBUS.dsLoaiSP == null){
            bus.docDSLoaiSP();
        }
        Vector header = new Vector();
        header.add("Mã loại");
        header.add("Tên loại");
      
        model = new DefaultTableModel(header,0);
                        
        for(LoaiSPDTO sp : LoaiSPBUS.dsLoaiSP){
            Vector row = new Vector();
            row.add(sp.getMaloai());
            row.add(sp.getTenloai());
            
            model.addRow(row);
        }
        tbloaisp.setModel(model);
    }
    
    public void showDSLoaiSP(ArrayList<LoaiSPDTO> ds){
        Vector header = new Vector();
        header.add("Mã loại");
        header.add("Tên loại");
        
        model = new DefaultTableModel(header,0);
        
        for(LoaiSPDTO sp : ds){
            Vector row = new Vector();
            row.add(sp.getMaloai());
            row.add(sp.getTenloai());
            row.add(sp.getMaloai());
            
            model.addRow(row);
        }
        tbloaisp.setModel(model);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoaiSPGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoaiSPGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoaiSPGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoaiSPGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoaiSPGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btSua;
    private javax.swing.JButton btThem;
    private javax.swing.JButton btXoa;
    private javax.swing.JButton btlammoi;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbMaloai;
    private javax.swing.JLabel lbTTloaisp;
    private javax.swing.JLabel lbTenloai;
    private javax.swing.JTable tbloaisp;
    private javax.swing.JTextField txMaloai;
    private javax.swing.JTextField txTenloai;
    // End of variables declaration//GEN-END:variables
}
