/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import BUS.LoaiSPBUS;
import BUS.SanPhamBUS;
import DTO.SanPhamDTO;
import Tool.ID;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javafx.scene.control.Cell;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import org.apache.poi.ss.usermodel.CellType;
import org.apache.poi.ss.usermodel.Sheet;
import org.apache.poi.xssf.usermodel.XSSFRow;
import org.apache.poi.xssf.usermodel.XSSFSheet;
import org.apache.poi.xssf.usermodel.XSSFWorkbook;

/**
 *
 * @author ASUS
 */
public class SanPhamGUI extends javax.swing.JFrame {
    DefaultTableModel model;
    /**
     * Creates new form Product
     */
    public SanPhamGUI() {
        initComponents();
        docDSSP();
        LoaiSPGUI loaiSP = new LoaiSPGUI();
        loaiSP.docDSLoaiSP();
        txMasp.setText(ID.createNewSP());
        for (int i=0;i<LoaiSPBUS.dsLoaiSP.size();i++){
            cbbMaLoai.addItem(LoaiSPBUS.dsLoaiSP.get(i).getMaloai());
        }
        
        txTensp.addKeyListener(new KeyAdapter() {
            @Override
            public void keyPressed(KeyEvent e){
                if(e.getKeyCode()==KeyEvent.VK_ENTER)
                    txDongia.requestFocus();
            }
        });
        txDongia.addKeyListener(new KeyAdapter() {
            @Override
            public void keyPressed(KeyEvent e){
                if(e.getKeyCode()==KeyEvent.VK_ENTER)
                    txSoluong.requestFocus();
            }
        });
        txSoluong.addKeyListener(new KeyAdapter() {
            @Override
            public void keyPressed(KeyEvent e){
                if(e.getKeyCode()==KeyEvent.VK_ENTER)
                    txDonvitinh.requestFocus();
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lbTTsp = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        lbMasp = new javax.swing.JLabel();
        lbTensp = new javax.swing.JLabel();
        lbMaloai = new javax.swing.JLabel();
        txMasp = new javax.swing.JTextField();
        txTensp = new javax.swing.JTextField();
        lbDongia = new javax.swing.JLabel();
        lbSoluong = new javax.swing.JLabel();
        lbDonvitinh = new javax.swing.JLabel();
        txDongia = new javax.swing.JTextField();
        txSoluong = new javax.swing.JTextField();
        txDonvitinh = new javax.swing.JTextField();
        btThem = new javax.swing.JButton();
        btSua = new javax.swing.JButton();
        btLammoi = new javax.swing.JButton();
        btXoa = new javax.swing.JButton();
        lbTrangThai = new javax.swing.JLabel();
        cbbTrangThai = new javax.swing.JComboBox<>();
        cbbMaLoai = new javax.swing.JComboBox<>();
        txTimKiem = new javax.swing.JTextField();
        btTimKiem = new javax.swing.JButton();
        cbbTimKiem = new javax.swing.JComboBox<>();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tbSanPham = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        lbTong = new javax.swing.JLabel();
        txTong = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));

        lbTTsp.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        lbTTsp.setForeground(new java.awt.Color(0, 0, 102));
        lbTTsp.setIcon(new javax.swing.ImageIcon("D:\\java\\MaketMini\\src\\icon\\icons8-product-64.png")); // NOI18N
        lbTTsp.setText("Quản lý sản phẩm");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(137, 137, 137)
                .addComponent(lbTTsp)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbTTsp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel2.setBackground(new java.awt.Color(204, 204, 255));

        lbMasp.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        lbMasp.setText("Mã sản phẩm");

        lbTensp.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        lbTensp.setText("Tên sản phẩm");

        lbMaloai.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        lbMaloai.setText("Mã loại");

        txMasp.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        txMasp.setEnabled(false);

        txTensp.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N

        lbDongia.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        lbDongia.setText("Đơn Giá");

        lbSoluong.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        lbSoluong.setText("Số Lượng");

        lbDonvitinh.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        lbDonvitinh.setText("Đơn vị tính");

        txDongia.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N

        txSoluong.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N

        txDonvitinh.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N

        btThem.setBackground(new java.awt.Color(255, 255, 255));
        btThem.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        btThem.setIcon(new javax.swing.ImageIcon("D:\\java\\MaketMini\\src\\icon\\icons8-add-24.png")); // NOI18N
        btThem.setText("Thêm");
        btThem.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        btThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btThemActionPerformed(evt);
            }
        });

        btSua.setBackground(new java.awt.Color(255, 255, 255));
        btSua.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        btSua.setIcon(new javax.swing.ImageIcon("D:\\java\\MaketMini\\src\\icon\\icons8-edit-24.png")); // NOI18N
        btSua.setText("Sửa");
        btSua.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        btSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSuaActionPerformed(evt);
            }
        });

        btLammoi.setBackground(new java.awt.Color(255, 255, 255));
        btLammoi.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        btLammoi.setIcon(new javax.swing.ImageIcon("D:\\java\\MaketMini\\src\\icon\\icons8-refresh-24.png")); // NOI18N
        btLammoi.setText("Làm mới");
        btLammoi.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        btLammoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLammoiActionPerformed(evt);
            }
        });

        btXoa.setBackground(new java.awt.Color(255, 255, 255));
        btXoa.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        btXoa.setIcon(new javax.swing.ImageIcon("D:\\java\\MaketMini\\src\\icon\\icons8-delete-24.png")); // NOI18N
        btXoa.setText("Xóa");
        btXoa.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        btXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btXoaActionPerformed(evt);
            }
        });

        lbTrangThai.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        lbTrangThai.setText("Trạng thái");

        cbbTrangThai.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        cbbTrangThai.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Đang bán", "Hết hàng" }));

        cbbMaLoai.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N

        btTimKiem.setBackground(new java.awt.Color(255, 255, 255));
        btTimKiem.setIcon(new javax.swing.ImageIcon("D:\\java\\MaketMini\\src\\icon\\icons8-search-24.png")); // NOI18N
        btTimKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btTimKiemActionPerformed(evt);
            }
        });

        cbbTimKiem.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        cbbTimKiem.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Mã SP", "Tên SP", "Trạng thái" }));
        cbbTimKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbbTimKiemActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(106, 106, 106)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbMasp)
                    .addComponent(lbTensp)
                    .addComponent(lbTrangThai, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(53, 53, 53)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbbTrangThai, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txTensp, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txMasp, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(75, 75, 75)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbMaloai)
                                    .addComponent(lbDongia))
                                .addGap(51, 51, 51)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cbbMaLoai, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txDongia, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                .addGap(46, 46, 46)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbSoluong)
                                    .addComponent(lbDonvitinh))
                                .addGap(27, 27, 27)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txSoluong, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txDonvitinh, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                .addComponent(txTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cbbTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(65, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(btThem, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(136, 136, 136)
                        .addComponent(btSua, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(176, 176, 176)
                        .addComponent(btXoa, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btLammoi, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(136, 136, 136))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbMasp)
                    .addComponent(txMasp, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbMaloai)
                    .addComponent(cbbMaLoai, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbSoluong)
                    .addComponent(txSoluong, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbTensp)
                    .addComponent(txTensp, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbDongia)
                    .addComponent(txDongia, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbDonvitinh)
                    .addComponent(txDonvitinh, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbTrangThai)
                            .addComponent(cbbTrangThai, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 103, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btThem, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btSua, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btXoa, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btLammoi, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(29, 29, 29)
                        .addComponent(btTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txTimKiem, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbbTimKiem, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );

        jPanel4.setBackground(new java.awt.Color(204, 204, 255));

        tbSanPham.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        tbSanPham.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Mã sản phẩm", "Tên sản phẩm", "Mã loại", "Đơn giá", "Số lượng", "Đơn vị tính", "Trạng thái"
            }
        ));
        tbSanPham.setRowHeight(25);
        tbSanPham.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbSanPhamMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(tbSanPham);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 1434, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(204, 204, 255));

        lbTong.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        lbTong.setText("Tổng");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txTong, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lbTong, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(58, 58, 58))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txTong, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbTong, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 34, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btThemActionPerformed
         //TODO add your handling code here:
        try {
            SanPhamDTO sp = new SanPhamDTO(); 
            sp.setMasp(ID.createNewSP());
            if(cbbTrangThai.getItemAt(cbbTrangThai.getSelectedIndex()).equals("Đang bán")){
                sp.setTrangthai(true);
            }
            else{
                sp.setTrangthai(false);
            }
            sp.setTensp(txTensp.getText());
            sp.setMaloai(cbbMaLoai.getItemAt(cbbMaLoai.getSelectedIndex()));
            sp.setDongia(Integer.parseInt(txDongia.getText()));
            sp.setSoluong(Integer.parseInt(txSoluong.getText())); 
            sp.setDVT(txDonvitinh.getText()); 
            SanPhamBUS bus = new  SanPhamBUS();
            bus.themSP(sp);

            JOptionPane.showMessageDialog(null, "Thêm sản phẩm thành công");

            txMasp.setText(ID.createNewSP());
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Thêm sản phẩm không thành công");
        }
        showDSSP(SanPhamBUS.dssp);  //để đây thì jtable tự sắp xếp lại        
    }//GEN-LAST:event_btThemActionPerformed

    private void btSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSuaActionPerformed
        // TODO add your handling code here:
        int i= tbSanPham.getSelectedRow();
                if(i>=0){
                    try {
                        SanPhamDTO sp = new SanPhamDTO();
                        sp.setMasp(txMasp.getText());
                        sp.setTensp(txTensp.getText());
                        sp.setMaloai(cbbMaLoai.getItemAt(cbbMaLoai.getSelectedIndex()));
                        
                        if(cbbTrangThai.getItemAt(cbbTrangThai.getSelectedIndex()).equals("Đang bán")){
                            sp.setTrangthai(true);
                        }
                        else{
                            sp.setTrangthai(false);
                        } 
                        
                        sp.setDongia(Integer.parseInt(txDongia.getText()));
                        sp.setSoluong(Integer.parseInt(txSoluong.getText())); 
                        sp.setDVT(txDonvitinh.getText()); 
                      
                        SanPhamBUS bus = new SanPhamBUS();
                        bus.suaSP(sp);
                        bus.docDSSP();
                        showDSSP(SanPhamBUS.dssp);

                    } catch (Exception ex) {
                        JOptionPane.showMessageDialog(null, "Sửa sản phẩm không thành công");
                    }
                }
                else{
                    JOptionPane.showMessageDialog(null, "Mời bạn chọn dòng cần sửa");
                }
    }//GEN-LAST:event_btSuaActionPerformed

    private void btXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btXoaActionPerformed
        // TODO add your handling code here:
        String ma = txMasp.getText();
        int i= tbSanPham.getSelectedRow();
            try {
                if(i>=0){
                        SanPhamBUS bus = new SanPhamBUS();
                        bus.xoaSP(ma);
                        bus.docDSSP();
                        showDSSP(SanPhamBUS.dssp);
                }
            } catch (Exception ex) {
                Logger.getLogger(KhachHangGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btXoaActionPerformed

    private void btLammoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLammoiActionPerformed
        // TODO add your handling code here:
        txMasp.setText(ID.createNewSP());
        txTensp.setText("");
        txDongia.setText("");
        txSoluong.setText("");
        txDonvitinh.setText("");
        //cbbTrangThai.setSelected(false);
    }//GEN-LAST:event_btLammoiActionPerformed

    private void tbSanPhamMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbSanPhamMouseClicked
        // TODO add your handling code here:
        int i = tbSanPham.getSelectedRow();
        if(i>=0){
            txMasp.setText(tbSanPham.getValueAt(i, 0)+ "");
            txTensp.setText(tbSanPham.getValueAt(i, 1)+ "");
            cbbMaLoai.setSelectedItem(tbSanPham.getValueAt(i, 2)+ "");
            txDongia.setText(tbSanPham.getValueAt(i, 3)+ "");
            txSoluong.setText(tbSanPham.getValueAt(i, 4)+ "");
            txDonvitinh.setText(tbSanPham.getValueAt(i, 5)+ "");
            cbbTrangThai.setSelectedItem(tbSanPham.getValueAt(i, 6)+ "");
        }
    }//GEN-LAST:event_tbSanPhamMouseClicked

    private void btTimKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btTimKiemActionPerformed
        // TODO add your handling code here:
            SanPhamBUS bus=new SanPhamBUS();
            ArrayList<SanPhamDTO> kq=new ArrayList<>();
                if(cbbTimKiem.getSelectedItem().equals("Mã SP")){
                   SanPhamDTO sp=bus.timKiemMaSP(SanPhamBUS.dssp, txTimKiem.getText());
                    if(sp!=null){
                        kq.add(sp);
                    }
                }
                else if(cbbTimKiem.getSelectedItem().equals("Tên SP")){
                    kq=bus.timKiemTenSP(SanPhamBUS.dssp,txTimKiem.getText());
                    for(SanPhamDTO sp : kq){
                    }
                }
                else if(cbbTimKiem.getSelectedItem().equals("Trạng thái")){
                    kq=bus.timKiemTrangthaiSP(txTimKiem.getText());
                    for(SanPhamDTO sp : kq){
                    }
                }
                if(kq.size()==0){
                    JOptionPane.showMessageDialog(null, "không có sản phẩm mà bạn cần tìm");
                }
                else{
                    showDSSP(kq);
                }
        
    }//GEN-LAST:event_btTimKiemActionPerformed

    private void cbbTimKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbbTimKiemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbbTimKiemActionPerformed

    public void docDSSP(){
    SanPhamBUS bus = new SanPhamBUS();
        if(SanPhamBUS.dssp == null){
            bus.docDSSP();
        }
        Vector header = new Vector();
        header.add("Mã sản phẩm");
        header.add("Tên sản phẩm");
        header.add("Mã loại");
        header.add("Đơn giá");
        header.add("Số lượng");
        header.add("Đơn vị tính");
        header.add("Trạng thái");
      
        model = new DefaultTableModel(header,0);
                        
        for(SanPhamDTO sp : SanPhamBUS.dssp){
            Vector row = new Vector();
            row.add(sp.getMasp());
            row.add(sp.getTensp());
            row.add(sp.getMaloai());
            row.add(sp.getDongia());
            row.add(sp.getSoluong());
            row.add(sp.getDVT());
            if(sp.getTrangthai()){
                row.add("Đang bán");
            }
            else{
                row.add("Hết hàng");
            }
            model.addRow(row);
        }
        tbSanPham.setModel(model);
    }
    public void showDSSP(ArrayList<SanPhamDTO> ds){
        Vector header = new Vector();
        header.add("Mã sản phẩm");
        header.add("Tên sản phẩm");
        header.add("Mã loại");
        header.add("Đơn giá");
        header.add("Số lượng");
        header.add("Đơn vị tính");
        header.add("Trạng thái");
       
        model = new DefaultTableModel(header,0);
        
        for(SanPhamDTO sp : ds){
            Vector row = new Vector();
            row.add(sp.getMasp());
            row.add(sp.getTensp());
            row.add(sp.getMaloai());
            row.add(sp.getDongia());
            row.add(sp.getSoluong());
            row.add(sp.getDVT());
            if(sp.getTrangthai()){
                row.add("Đang bán");
            }
            else{
                row.add("Hết hàng");
            }
            
            model.addRow(row);
        }
        tbSanPham.setModel(model);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SanPhamGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SanPhamGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SanPhamGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SanPhamGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SanPhamGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btLammoi;
    private javax.swing.JButton btSua;
    private javax.swing.JButton btThem;
    private javax.swing.JButton btTimKiem;
    private javax.swing.JButton btXoa;
    private javax.swing.JComboBox<String> cbbMaLoai;
    private javax.swing.JComboBox<String> cbbTimKiem;
    private javax.swing.JComboBox<String> cbbTrangThai;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JLabel lbDongia;
    private javax.swing.JLabel lbDonvitinh;
    private javax.swing.JLabel lbMaloai;
    private javax.swing.JLabel lbMasp;
    private javax.swing.JLabel lbSoluong;
    private javax.swing.JLabel lbTTsp;
    private javax.swing.JLabel lbTensp;
    private javax.swing.JLabel lbTong;
    private javax.swing.JLabel lbTrangThai;
    private javax.swing.JTable tbSanPham;
    private javax.swing.JTextField txDongia;
    private javax.swing.JTextField txDonvitinh;
    private javax.swing.JTextField txMasp;
    private javax.swing.JTextField txSoluong;
    private javax.swing.JTextField txTensp;
    private javax.swing.JTextField txTimKiem;
    private javax.swing.JTextField txTong;
    // End of variables declaration//GEN-END:variables
}
